# docker-compose.yml
networks:
  ray-autoscaler-net:
    driver: bridge
    name: ray-autoscaler-net

services:
  ray-head:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: ray-autoscaler-node
    container_name: ray-head
    networks:
      - ray-autoscaler-net
    ports:
      - "8265:8265" # Dashboard
      - "10001:10001" # Client 連線
      - "6379:6379" # GCS
    command: >
      ray start --head
      --node-ip-address=ray-head
      --port=6379
      --dashboard-host=0.0.0.0
      --dashboard-port=8265
      --ray-client-server-port=10001
      --block
    env_file: .env

  # First static worker node for testing the cluster netwoking
  # ray-worker-1:
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile
  #   container_name: ray-worker-1
  #   networks:
  #     - ray-autoscaler-net
  #   depends_on:
  #     - ray-head
  #   command: >
  #     ray start
  #     --address=ray-head:6379
  #     --block
  #   env_file: .env
