# docker-compose.yml
networks:
  ray-autoscaler-net:
    driver: bridge
    name: ray-autoscaler-net

services:
  ray-head:
    build:
      context: .
      dockerfile: docker/ray_head/dockerfile
    image: ray-autoscaler-node
    container_name: ray-head
    networks:
      - ray-autoscaler-net
    ports:
      - "8265:8265" # Dashboard
      - "10001:10001" # Client 連線
      - "6379:6379" # GCS
      - "8000:8000" # Backend
    command: >
      bash -c "
      ray start --head
      --node-ip-address=ray-head
      --port=6379
      --dashboard-host=0.0.0.0
      --dashboard-port=8265
      --ray-client-server-port=10001 &&
      python -m uvicorn backend.main:app --host 0.0.0.0 --port  8000
      "
    env_file: .env
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import ray; ray.init(address='ray-head:6379', ignore_reinit_error=True)",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # backend:
  #   build:
  #     context: .
  #     dockerfile: docker/backend/dockerfile
  #   image: ds-backend
  #   container_name: ds-backend
  #   networks:
  #     - ray-autoscaler-net
  #   depends_on:
  #     ray-head:
  #       condition: service_healthy
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - RAY_ADDRESS=ray-head:6379
  #   command: >
  #     bash -c "
  #     ray start --address=ray-head:6379 --num-cpus=0 --block &
  #     sleep 5 &&
  #     python -m uvicorn backend.main:app --host 0.0.0.0 --port 8000
  #     "
  # First static worker node for testing the cluster netwoking
  # ray-worker-1:
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile
  #   container_name: ray-worker-1
  #   networks:
  #     - ray-autoscaler-net
  #   depends_on:
  #     - ray-head
  #   command: >
  #     ray start
  #     --address=ray-head:6379
  #     --block
  #   env_file: .env
