# docker/Dockerfile
FROM python:3.11-slim

WORKDIR /app
COPY docker-requirements.txt .
RUN pip install --no-cache-dir  -r docker-requirements.txt

# Expose ports for RAY
EXPOSE 6379 8265 10001 8076 8080

